# Generated by Django 2.1.5 on 2019-03-31 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tliublog', '0002_auto_20190401_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tliublog.Category', verbose_name='分类'),
        ),
    ]
